

services:
  backend:
    # C 51: Dùng thuộc tính image thay vì build
    image: alextruonggg/mern-backend:1.0
    # C 53: Ánh xạ port 5000 của máy local vào 5000 của container
    ports:
      - "5000:5000"
    # C 55: Cấu hình biến môi trường kết nối MongoDB Atlas
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://TruongVanLuan:luan12345@cluster0.5d1ctxz.mongodb.net/cloud_lab?retryWrites=true&w=majority

  frontend:
    # C 52: Dùng thuộc tính image cho frontend
    image: alextruonggg/mern-frontend:1.0
    # C 54: Ánh xạ port cho Frontend (Ví dụ: 3000 hoặc 5173 tùy ứng dụng của bạn)
    ports:
      - "5173:4173"
    # Đảm bảo frontend chạy sau khi backend đã khởi động
    depends_on:
      - backend